ALTER LOGIN $(userName)
ADD CREDENTIAL sysadmin_ekm_cred;
GO

CREATE ASYMMETRIC KEY TDE_KEY
FROM PROVIDER [AzureKeyVault_EKM_Prov]
WITH PROVIDER_KEY_NAME = 'ContosoMasterKey',
CREATION_DISPOSITION = OPEN_EXISTING;

CREATE LOGIN TDE_Login
FROM ASYMMETRIC KEY TDE_KEY ;
GO

CREATE CREDENTIAL Azure_EKM_TDE_credential
    WITH IDENTITY = $(kvName),
    SECRET = $(kvSecret)
FOR CRYPTOGRAPHIC PROVIDER AzureKeyVault_EKM_Prov;

ALTER LOGIN TDE_Login 
ADD CREDENTIAL Azure_EKM_TDE_credential ;
GO

USE $(dbName);
GO
CREATE DATABASE ENCRYPTION KEY
WITH ALGORITHM  = AES_256
ENCRYPTION BY SERVER ASYMMETRIC KEY TDE_KEY;
GO

IF HOST_NAME() like '%sql0'L
    USE [master];
    GO
    ALTER DATABASE $(dbName)
    SET ENCRYPTION ON ;
    GO
ELSE
    PRINT 'secondary node, nothing to encrypt'
